### ISSUE TITLE
Boot manager entry with wrong 'Linpus lite' distribution name is displayed when starting Netrunner Debian from live USB

### ISSUE THREAD

**Issue by notuxius** [blue-systems/netrunner-issues-old#99] opened 2018-12-13 20:25 UTC

**Comment by llelectronics** [comment] 2018-12-13 20:43
Can't reproduce it here. Can you retest this please I fear it might be something else you might've tested in the past that is giving you this strange entry.

**Comment by star-buck** [comment] 2018-12-13 21:03
I will also check this with latest iso.

**Comment by star-buck** [comment] 2018-12-14 21:59
didnt see Linpus anywhere.
@notuxius : did you use Linpus on your side, or downloaded it anywhere in the past?

**Comment by notuxius** [comment] 2018-12-15 08:51
Here is shot of my boot manager after pressing F12 on Lenovo laptop

![img_20181214_152510](https://user-images.githubusercontent.com/2657014/50041062-3ef66280-0057-11e9-9f06-2bd24f5e6c41.jpg)

**Comment by llelectronics** [comment] 2018-12-15 08:58
Like expected that is an issue of that particular USB Stick that had Linpus on there before I assume

**Comment by star-buck** [comment] 2018-12-15 08:59
Interesting.
@Alexander: did this usb stick had Linpus on before?

**Comment by notuxius** [comment] 2018-12-15 10:09
Same Linpus entry on other USB drive - tried writing with SUSE image writer and with Gnome Disks.
Writing Rolling on same USB drive shows 'EFI USB Device' entry instead of Linpus in boot manager.

**Comment by star-buck** [comment] 2018-12-15 11:11
Please answer the question:

Did any of you ever use or downloaded Linpus recently or in the past?

**Comment by notuxius** [comment] 2018-12-15 18:43
This is possible issue on my side and i don't remember if i tried Linpus - there was a day when i launched a few dozens distros) from USB drive in one day (from other then current USB stick) - and still:
Linpus is display for USB device on these distros:
fedora, opensuse, netrunner debian, ubuntu
and not displayed on these:
manjaro, rolling, kaos, kali

**Comment by star-buck** [comment] 2018-12-15 19:17
Okay, closing here then.

@Alexander:
Although this was a potential real issue, regarding the other stuff please stick to REAL bugs on Netrunner for now, like marble no longer searching correctly, etc. Dont clog this issue tracker with suggestions or ideas what you "like better". Thanks.

**Closed as completed by star-buck** 2018-12-15 19:18 UTC
