### ISSUE TITLE
Firefox: youtube: clicking on next video mutes the audio output, so next video starts without sound

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-issues-old#137] opened 2018-12-17 20:29 UTC
could be firefox, the firefox integration plugin or the volume 7 mixer or something unknown.
Since version 22 of volume mixer is installed, we could update to v23 and see if it fixes the issue

Unfortunately this package depends on netrunner black theme so i cant uninstall and update manually.

@NuLogicSystems : Can you check if that is working on Rolling?
@notuxius : Can you help investigate and look for causes or reports?

**Comment by llelectronics** [comment] 2018-12-18 10:09
Disabling Plasma Browser Integration Plugin makes it work again. I assume the media player integration it allows might cause the issue.

**Comment by llelectronics** [comment] 2018-12-18 13:28
Not fixed yet. Seems to occur everytime winvolume7mixer is opened.

**Comment by star-buck** [comment] 2018-12-18 13:30
Can you spin a new package with updated version?

**Comment by llelectronics** [comment] 2018-12-18 13:31
I tried that already.

**Comment by notuxius** [comment] 2018-12-18 13:38
Can't reproduce it - audio is present when switching next videos on yt site in ff

**Comment by star-buck** [comment] 2018-12-18 13:44
Then try to do what has suggested here. Open volumemixer, open two seperate
windows with both a youtube video and then switch one in one window, etc.
Find a reproducible pattern.

**Comment by notuxius** [comment] 2018-12-18 16:44
1. If there were additional checkboxes checked for current audio stream in win7 mixer - like Volume Boost, Show Channels - they are unchecked on next video load.
2. Reloading page with audio doesn't mutes it - creates plus one audio stream in the mixer widget.
3. Closing current tab with audio and then restoring it also mutes audio - it creates plus one audio stream with volume level at 0% in the mixer widget.
4. Pressing back button in Firefox also mutes audio for the page.
5. Volume slider of current audio source jumps up on random percent values - like from 12 to 85 or from 20 to 96, from 82 to 85, 100 to 86, etc.
6. Not always reproducible - very often ~4 of 5 times - audio stream volume slider changes volume sound percentage and not mutes.

**Comment by star-buck** [comment] 2018-12-18 17:06
Again, lets try latest version:
https://store.kde.org/p/1100894/

Also lets post all our findings via an issue here:
https://github.com/Zren/plasma-applet-volumewin7mixer/issues

**Comment by llelectronics** [comment] 2018-12-18 17:18
I already filled in a bug for them to release version 23 as otherwise dci won't pick it up.

**Comment by star-buck** [comment] 2018-12-18 17:26
But isnt v23 released as plasmoid in store.kde.org?

**Comment by llelectronics** [comment] 2018-12-18 17:29
I can build it manually. Watch file is looking for another url where it can download the source directly: https://github.com/dci-extras-packaging/plasma-widget-volumewin7mixer/blob/master/debian/watch

**Comment by notuxius** [comment] 2018-12-19 14:16
Can't reproduce this bug in latest (12.19) live iso

**Comment by star-buck** [comment] 2018-12-20 10:30
seems fixed now.

**Closed as completed** 2018-12-20 10:31 UTC
Labels: bug, blocking
